export { ReactComponent as ShoppingCartIcon } from './shopping-cart.svg'
export { ReactComponent as PlusIcon } from './plus.svg'
export { ReactComponent as MinusIcon } from './minus.svg'
export { ReactComponent as LinkIcon } from './link.svg'
export { ReactComponent as NotFoundIcon } from './not-found.svg'
export { ReactComponent as EmptyIcon } from './empty.svg'
export { ReactComponent as LeftIcon } from './left.svg'
